# Generated by Django 3.2.5 on 2021-07-15 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginregistro', '0001_initial'),
        ('main', '0002_comment_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='destiny',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ownmessages', to='loginregistro.user'),
            preserve_default=False,
        ),
    ]
